### ISSUE TITLE
Save and load model with CRF

### ISSUE THREAD

**Issue by Erechtheus** [xuxingya/tf2crf#17] opened 2020-10-20 12:23 UTC
I am unable to load a trained model using the CRF layer. Could you please extend the minimal example from your github page? The example code, allready contains code to store a model, but no example to load the model. 

```
import tensorflow as tf
new_model = tf.keras.models.load_model('model')
```
raises an error

```
Traceback (most recent call last):
  File "<input>", line 3, in <module>
  File "/home/philippe/tools/anaconda/envs/code/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 190, in load_model
    return saved_model_load.load(filepath, compile)
  File "/home/philippe/tools/anaconda/envs/code/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 125, in load
    model.compile(**saving_utils.compile_args_from_training_config(
  File "/home/philippe/tools/anaconda/envs/code/lib/python3.8/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 215, in compile_args_from_training_config
    loss = _deserialize_nested_config(losses.deserialize, loss_config)
  File "/home/philippe/tools/anaconda/envs/code/lib/python3.8/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 255, in _deserialize_nested_config
    return deserialize_fn(config)
  File "/home/philippe/tools/anaconda/envs/code/lib/python3.8/site-packages/tensorflow/python/keras/losses.py", line 1831, in deserialize
    return deserialize_keras_object(
  File "/home/philippe/tools/anaconda/envs/code/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 392, in deserialize_keras_object
    raise ValueError('Unknown ' + printable_module_name + ':' + object_name)
ValueError: Unknown loss function:loss
```

I also tried many workarounds, but failed to load a model.

**Comment by xuxingya** [comment] 2020-10-21 03:29
I'm sorry I don't explain how to save and load model.
Currently, I find it difficult to load the model directly. So you need to load the model weights instead.
For example:
```
tf.keras.models.save_model(model, '1')
model.load_weights('1/variables/variables')
```
or
```
model.save_weights('model.h5')
model.load_weights('model.h5')
```

**Comment by wfge** [comment] 2020-10-21 06:17
> I am unable to load a trained model using the CRF layer. Could you please extend the minimal example from your github page? The example code, allready contains code to store a model, but no example to load the model.
> 
> ```
> import tensorflow as tf
> new_model = tf.keras.models.load_model('model')
> ```
> 
> raises an error
> 
> ```
> Traceback (most recent call last):
>   File "<input>", line 3, in <module>
>   File "/home/philippe/tools/anaconda/envs/code/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 190, in load_model
>     return saved_model_load.load(filepath, compile)
>   File "/home/philippe/tools/anaconda/envs/code/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 125, in load
>     model.compile(**saving_utils.compile_args_from_training_config(
>   File "/home/philippe/tools/anaconda/envs/code/lib/python3.8/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 215, in compile_args_from_training_config
>     loss = _deserialize_nested_config(losses.deserialize, loss_config)
>   File "/home/philippe/tools/anaconda/envs/code/lib/python3.8/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 255, in _deserialize_nested_config
>     return deserialize_fn(config)
>   File "/home/philippe/tools/anaconda/envs/code/lib/python3.8/site-packages/tensorflow/python/keras/losses.py", line 1831, in deserialize
>     return deserialize_keras_object(
>   File "/home/philippe/tools/anaconda/envs/code/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 392, in deserialize_keras_object
>     raise ValueError('Unknown ' + printable_module_name + ':' + object_name)
> ValueError: Unknown loss function:loss
> ```
> 
> I also tried many workarounds, but failed to load a model.

----

maybe u can do like this
---
from tf2crf import CRF
def my_load_model(file_path):
    my_object={"loss":CRF.loss,"accuracy":CRF.accuracy}
    model_loaded = tf.keras.models.load_model(file_path,custom_objects=my_object)
    return model_loaded

**Comment by xuxingya** [comment] 2020-10-21 08:00
I'm sorry I don't explain how to save and load the model.
Currently, I find it difficult to load the model directly. So you need to
load the model weights instead.
You can use:
tf.keras.models.save_model(model, '1')
model.load_weights('1/variables/variables')
or
model.save_weights('model.h5')
model.load_weights('model.h5')

**Comment by wfge** [comment] 2020-10-21 12:33
> I am unable to load a trained model using the CRF layer. Could you please extend the minimal example from your github page? The example code, allready contains code to store a model, but no example to load the model.
> 
> ```
> import tensorflow as tf
> new_model = tf.keras.models.load_model('model')
> ```
> 
> raises an error
> 
> ```
> Traceback (most recent call last):
>   File "<input>", line 3, in <module>
>   File "/home/philippe/tools/anaconda/envs/code/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 190, in load_model
>     return saved_model_load.load(filepath, compile)
>   File "/home/philippe/tools/anaconda/envs/code/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 125, in load
>     model.compile(**saving_utils.compile_args_from_training_config(
>   File "/home/philippe/tools/anaconda/envs/code/lib/python3.8/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 215, in compile_args_from_training_config
>     loss = _deserialize_nested_config(losses.deserialize, loss_config)
>   File "/home/philippe/tools/anaconda/envs/code/lib/python3.8/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 255, in _deserialize_nested_config
>     return deserialize_fn(config)
>   File "/home/philippe/tools/anaconda/envs/code/lib/python3.8/site-packages/tensorflow/python/keras/losses.py", line 1831, in deserialize
>     return deserialize_keras_object(
>   File "/home/philippe/tools/anaconda/envs/code/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 392, in deserialize_keras_object
>     raise ValueError('Unknown ' + printable_module_name + ':' + object_name)
> ValueError: Unknown loss function:loss
> ```
> 
> I also tried many workarounds, but failed to load a model.

---
maybe you can load model like this
---

from tf2crf import CRF
def load_my_model(file_path):
      my_object={"loss":CRF.loss,"accuracy":CRF.accuracy}
      model_loaded = tf.keras.models.load_model(file_path,custom_objects=my_object)
 return model_loaded


because the loss function and accuracy is defined by yourself,not defined by Keras API

**Comment by Erechtheus** [comment] 2020-10-21 20:04
Thank you @wfge  and @xuxingya. What seems to work for me is:

Saving:
```
with open("/tmp/model.json", 'w') as f:
    params = model.to_json()
    json.dump(json.loads(params), f, sort_keys=True, indent=4)

model.save_weights("/tmp/model.weight")
```

Loading:
```
f = open("/tmp/model.json")
model = model_from_json(f.read(), custom_objects={'CRF': CRF})
f.close()

model.load_weights("/tmp/model.weight")
```

However, I had to slightly change the _init_ method in your code. I will create a pull request

**Comment by xuxingya** [comment] 2020-10-22 01:51
I have merged the change.
Thank you for your contribution : )

**Comment by Erechtheus** [comment] 2020-10-22 07:28
I am glad I could help. The get_config method currently neither stores **sequence_lengths** nor **mask** variables. Not sure if these are relevant, but I did not manage to save this information. With my straight forward implementation, I had locking issues.

**Closed** 2020-12-03 05:59 UTC

**Comment by trisha-git** [comment] 2021-09-07 13:46
@Erechtheus Could you please mention the tensorflow version you are using? When I tried this approach with TF 2.5 I am getting an [open issue](https://github.com/tensorflow/addons/issues/2476) with CRF decoding. 
I also tried with TF 2.4, then I am getting an incosistency error of layers in weights and in architecture.

**Comment by xuxingya** [comment] 2021-09-08 02:05
I think this is caused by the version of tensorflow-addons, as the library
uses  the module for CRF decoding.

**Comment by trisha-git** [comment] 2021-09-08 08:03
I am using tensorflow-addons=0.14.0. Do you have any idea which version does not show this issue?
